// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Juneo-io/juneogo/snow/validators (interfaces: SupernetConnector)
//
// Generated by this command:
//
//	mockgen -package=validators -destination=snow/validators/mock_supernet_connector.go github.com/Juneo-io/juneogo/snow/validators SupernetConnector
//

// Package validators is a generated GoMock package.
package validators

import (
	context "context"
	reflect "reflect"

	ids "github.com/Juneo-io/juneogo/ids"
	gomock "go.uber.org/mock/gomock"
)

// MockSupernetConnector is a mock of SupernetConnector interface.
type MockSupernetConnector struct {
	ctrl     *gomock.Controller
	recorder *MockSupernetConnectorMockRecorder
}

// MockSupernetConnectorMockRecorder is the mock recorder for MockSupernetConnector.
type MockSupernetConnectorMockRecorder struct {
	mock *MockSupernetConnector
}

// NewMockSupernetConnector creates a new mock instance.
func NewMockSupernetConnector(ctrl *gomock.Controller) *MockSupernetConnector {
	mock := &MockSupernetConnector{ctrl: ctrl}
	mock.recorder = &MockSupernetConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupernetConnector) EXPECT() *MockSupernetConnectorMockRecorder {
	return m.recorder
}

// ConnectedSupernet mocks base method.
func (m *MockSupernetConnector) ConnectedSupernet(arg0 context.Context, arg1 ids.NodeID, arg2 ids.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectedSupernet", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectedSupernet indicates an expected call of ConnectedSupernet.
func (mr *MockSupernetConnectorMockRecorder) ConnectedSupernet(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectedSupernet", reflect.TypeOf((*MockSupernetConnector)(nil).ConnectedSupernet), arg0, arg1, arg2)
}
