name: build-arm64-debian-packages

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-jammy-arm64-package:
    runs-on: [self-hosted, linux, ARM64, jammy]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go version

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh

      - name: Install aws cli
        run: |
          sudo apt update
          sudo apt -y install awscli

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create debian package
        run: ./.github/workflows/build-deb-pkg.sh
        env:
          TAG: ${{ env.VERSION }}
          BUCKET: ${{ secrets.BUCKET }}
          ARCH: "arm64"
          RELEASE: "jammy"

  build-focal-arm64-package:
    runs-on: [self-hosted, linux, ARM64, focal]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go version

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh

      - name: Install aws cli
        run: |
          sudo apt update
          sudo apt -y install awscli

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create debian package
        run: ./.github/workflows/build-deb-pkg.sh
        env:
          TAG: ${{ env.VERSION }}
          BUCKET: ${{ secrets.BUCKET }}
          ARCH: "arm64"
          RELEASE: "focal"
